### ISSUE TITLE
Cannot register domain name

### ISSUE THREAD

**Issue by aequitas** [transip/gotransip#12]
## (Problem) Description
Cannot register domain name.

## Steps to reproduce
```go
client, _ := gotransip.NewSOAPClient(gotransip.ClientConfig{.....})
err := domain.Register(client, "example.com")
```

## Expected behaviour
Domain name is registred

## Actual behaviour
`SOAP Fault 204: Exception received from JSON Server: Invalid API signature, signature does not match the request.`

## Suggested fix
Looking at the code here: 

https://github.com/transip/gotransip/blob/master/domain/api.go#L126

It seems a domain name as string is passed as SOAP argument.
Where as the spec seems to indicate a Domain object is required:

https://api.transip.nl/docs/transip.nl/source-class-Transip_DomainService.html#307-318

**Comment by skoef** [comment]
Most of the code from `api.go` was a result of parsing the specs, but this seems to be implemented wrong indeed. I'll whip out my test-environment and see if I can fix this!

**Comment by aequitas** [comment]
@skoef I'm currently working on https://github.com/aequitas/terraform-provider-transip Is there a way to setup a test-environment for myself? Or do you have a staging/testing API endpoint that does not actually order anything so I can test it without creating costs?

**Comment by skoef** [comment]
@aequitas I've pushed a branch that should fix the issue. It involved some refactoring, but in the end it was for the better. Could you see if this indeed fixes your issue?

As for the test environment: sorry, there is currently no testing API endpoint. You could however test your code in readonly by setting your `ClientConfig.Mode` to `APIModeReadOnly`. Hope that works for you!

**Comment by aequitas** [comment]
Thanks! I'll check this out tomorrow and report back.

I'll also try out the readonly mode.

**Comment by skoef** [comment]
@aequitas any luck trying out the branch?

**Comment by aequitas** [comment]
@skoef sorry for the delay, I was sick the past days so this got a little off schedule.

I have tested domain creation just now and it is working as expected.

There is however some delay in the registration completing and the domain being available through the API, so doing a `GetInfo` on the domain just after `Register` resulting in this error: `SOAP Fault 102: One or more domains could not be found.` I will build in some retry/delay to resolve this.

I don't know if you can answer this for me but: if I `Register` and `Cancel` the same domain multiple times within a month. Do I have to pay for every time I register or will it all count as the same registration at the end of the month? It would not be possible to test the behavior of the API using the read only mode.

**Comment by skoef** [comment]
I'm glad the fix works for you! 

I can't comment on the delay between registering and seeing the domain in your API output, that's probably just how the backend works and beyond the scope of the API. Same goes for the billing period for domains. If you have any questions about that, please refer to our [knowledge base](https://www.transip.eu/knowledgebase/) or send a ticket to support@transip.eu.
