### ISSUE TITLE
Update tags to follow semver

### ISSUE THREAD

**Issue by ldez** [transip/gotransip#18]
## (Problem) Description

To be understandable by go module, the tags must follow [semver](https://semver.org/)

- https://github.com/golang/go/wiki/Modules#semantic-import-versioning

The tags `v5.8`, `v5.13`, `v5.14` are not supported.

- https://github.com/transip/gotransip/tags

## Steps to reproduce

```go
module github.com/yourusername/project

go 1.12

require (
	github.com/transip/gotransip v5.14
)
```

Run `go mod tidy`

## Expected behaviour

```go
module github.com/yourusername/project

go 1.12

require (
	github.com/transip/gotransip v5.14.0
)
```

## Actual behaviour

```go
module github.com/yourusername/project

go 1.12

require (
	github.com/transip/gotransip v0.0.0-20190614113603-efb64632cab7
)
```

## Suggested fix

Add tags without remove the previous tags:
- `v5.8.0` on `v5.8`
- `v5.13.0` on `v5.13`
- `v5.14.0` on `v5.14`

```bash
git tag v5.8.0 v5.8
git tag v5.13.0 v5.13
git tag v5.14.0 v5.14
git push --tags
```

**Comment by skoef** [comment]
You're absolutely right. The initial reason for tags like `v5.8.1` was that while following API specification `5.8`, there were some bugfixes in the golang client. Anyway, I just merged the implementation for API version `5.15` and properly tagged all versions. Thanks for pointing this out to us!
