### ISSUE TITLE
REST API Support

### ISSUE THREAD

**Issue by aequitas** [transip/gotransip#26]
I've developed a terraform provider using this library (https://github.com/aequitas/terraform-provider-transip) and was wondering if there is any effort doing on in porting this library to the REST API? I'd like to switch to using the REST API because of some of its feature.

**Comment by svenwiltink** [comment]
We are working on a v6 release of the gotransip library, which will use the REST API.

**Comment by aequitas** [comment]
Good to hear, anything you can tell about when to expect it?

**Comment by svenwiltink** [comment]
We don't have an exact release date yet, but we expect to have more news in the coming week or two. This issue will be updated as information becomes available.

**Comment by dionbosschieter** [comment]
Hi Johan,

We are happy to inform you that we have just released version 6.0 of the golang TransIP API client which uses the REST API.
Go and check it out at https://pkg.go.dev/github.com/transip/gotransip/v6?tab=doc.

Good luck with updating your terraform provider :)
