### ISSUE TITLE
Install dependency via dep

### ISSUE THREAD

**Issue by bartversluijs** [transip/gotransip#32]
## (Problem) Description

I'm trying to create a Golang project using [golang/dep](https://github.com/golang/dep), and I'm trying to install this project as a dependency. But I get errors, because the code uses `github.com/transip/gotransip/v6`, but that directory isn't found (obviously).

## Steps to reproduce

1. `dep init`
2. `dep ensure -add github.com/transip/gotransip@v6.0.3`

## Expected behaviour

When the dependency has been added, `dep` will install the dependency in the `vendor` directory and I can import `github.com/transip/gotransip` and use it.

## Actual behaviour

I get the following errors (and some more, but they're the same as the last 3):
```
Fetching sources...

Solving failure: No versions of github.com/transip/gotransip met constraints:
	v6.0.3: "github.com/transip/gotransip" imports "github.com/transip/gotransip/v6/authenticator", which contains malformed code: no package exists at "github.com/transip/gotransip/v6/authenticator"
	v6.0.2: Could not introduce github.com/transip/gotransip@v6.0.2, as it is not allowed by constraint ^6.0.3 from project github.com/vedicium/dehydrated-transip-dns01-go.
	v6.0.1: Could not introduce github.com/transip/gotransip@v6.0.1, as it is not allowed by constraint ^6.0.3 from project github.com/vedicium/dehydrated-transip-dns01-go.
	v6.0.0: Could not introduce github.com/transip/gotransip@v6.0.0, as it is not allowed by constraint ^6.0.3 from project github.com/vedicium/dehydrated-transip-dns01-go.
```

## Suggested fix

It looks like it crashes because it can't find `github.com/transip/gotransip/v6/authenticator`. Probably because it's found in `github.com/transip/gotransip/authenticator` and not in the v6 directory.

The imports should probably be changed to the root directory (`github.com/transip/gotransip`. I understand the `v6` is used, but isn't it better if you want to use the SOAP API, you just have to install the V5 version?

**Comment by svenwiltink** [comment]
The library doesn't work with `dep` anymore because we are using go modules. Modules were introduced in go 1.11 and is the successor of `dep`. Instead of trying to make `dep` work I suggest looking into modules instead.

some handy links:
- https://blog.golang.org/using-go-modules
- https://github.com/golang/go/wiki/Modules
- https://roberto.selbach.ca/intro-to-go-modules/

**Comment by bartversluijs** [comment]
Thanks for the quick response.
I'll try using modules instead.
