### ISSUE TITLE
Unable to order a Vps without addons

### ISSUE THREAD

**Issue by roaldnefs** [transip/gotransip#7]
## (Problem) Description
Unable to order a Vps without addons.

## Steps to reproduce

Running the following code results in a `panic: SOAP Fault 204: Exception received from JSON Server: Invalid API signature, signature does not match the request.`:
```go
package main

import (
  "github.com/transip/gotransip"
  "github.com/transip/gotransip/vps"
)

func main() {
  // create new TransIP API SOAP client
  c, err := gotransip.NewSOAPClient(gotransip.ClientConfig{
    AccountName: "accountname",
    PrivateKeyPath:  "/path/to/private/key",
  })
  if err != nil {
    panic(err.Error())
  }

  // order a VPS
  productName := "vps-bladevps-x1"
  addons := []string{}
  operatingSystemName := "ubuntu-18.04"
  hostname := "hostname"
  err = vps.OrderVps(c, productName, addons, operatingSystemName, hostname)
  if err != nil {
    panic(err.Error())
  }
}
```
If a non-existing addon (`addons := []string{'nonexisting'}`) is specified the client will successfully order the Vps.

## Expected behaviour
Should be able to order a Vps without having to add addons.

## Actual behaviour
Ordering a Vps without addons results in a `panic: SOAP Fault 204: Exception received from JSON Server: Invalid API signature, signature does not match the request.`.

## Suggested fix
_n/a_

**Comment by skoef** [comment]
That probably has something to do with the way the SOAP XML is built up vs. the way the signature parameters are built up. I'll look into it!
