### ISSUE TITLE
Create new release from master

### ISSUE THREAD

**Issue by mdbraber** [transip/gotransip#9]
I've written a [DNS provider plugin for the lego](https://github.com/xenolf/lego/pull/703) package to do a DNS-01 challenge for Let's Encrypt. It's currently slated to use the 5.8 release, but unfortunately there are several issues with that release (API errors that vanish when using master which generaters also much clearer errors). I see 5.8 is 13 commits behind master - would it be possible to create a new updated release?

**Comment by skoef** [comment]
You're right, I've just tagged the latest commit with `v5.8.1`. Since the versioning follows the PHP API versioning, I can only bump it on patch level.
